Tasks:
  - AdbPushTask:
      files:
        - "build-android-arm64-v8a/bin/libMllmRT.so"
        - "build-android-arm64-v8a/bin/libMllmCPUBackend.so"
        - "build-android-arm64-v8a/bin/mllm-params-inspector"
        - "build-android-arm64-v8a/bin/mllm-quantizer"
        - "build-android-arm64-v8a/bin/mllm-qwen2-vl-runner"
        - "build-android-arm64-v8a/bin/mllm-qwen2_5-vl-runner"
        - "build-android-arm64-v8a/bin/mllm-qwen3-runner"
        - "build-android-arm64-v8a/bin/mllm-qwen3-service"
        - "build-android-arm64-v8a/bin/mllm-deepseek-ocr-runner"
        - "build-android-arm64-v8a/bin/Mllm-Test-CPUKernel"
        - "build-android-arm64-v8a/bin/Mllm-Benchmark-EXT-STL-IntrusivePtr"

      to_path: "/data/local/tmp/mllm/bin/"
