Tasks:
 - ShellCommandTask:
     command: |
      export GOPROXY=https://goproxy.cn,direct
      export GOOS=android
      export GOARCH=arm64
      export CGO_ENABLED=1
      export ANDROID_NDK_HOME=/opt/ndk/android-ndk-r28b
      export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang
      export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang++
      
      export CGO_LDFLAGS="-L$(pwd)/build-android-arm64-v8a/bin -lMllmSdkC -lMllmRT -lMllmCPUBackend -llog"
      export CGO_CFLAGS="-I$(pwd) -I/tmp/mllm_build"
      
      cd mllm-cli && \
      echo "Running 'go mod tidy' to sync dependencies..." && \
      go mod tidy && \
      echo "Starting build..." && \
      go build -o ../build-android-arm64-v8a/bin/mllm_web_server -tags=mobile ./cmd/mllm-server/main.go