Tasks:
  - CMakeConfigTask:
      cmake_cfg_path: "build-sdk-osx"
      cmake_build_type: "Release"
      cmake_extra_args:
        - "-DMLLM_BUILD_ARM_BACKEND=ON"
        - '-DMLLM_CPU_BACKEND_COMPILE_OPTIONS="-march=native+fp16+fp16fml+dotprod+i8mm+sme"'
        - "-DMLLM_USE_BLAS=ON"
        - "-DMLLM_BLAS_VENDOR_ACCELERATE=ON"
        - "-DMLLM_KERNEL_USE_THREADS=ON"
        - "-DMLLM_KERNEL_THREADS_VENDOR_OPENMP=OFF"
        - "-DMLLM_KERNEL_USE_THREADS_VENDOR_MLLM=OFF"
        - "-DMLLM_KERNEL_THREADS_VENDOR_APPLE_GCD=ON"
        - "-DCMAKE_INSTALL_PREFIX=./mllm-sdk-osx"
  - CMakeBuildTask:
      cmake_cfg_path: "build-sdk-osx"
  - CMakeInstallTask:
      cmake_cfg_path: "build-sdk-osx"
