Tasks:
  - HexagonMakeTask:
      mllm_qnn_package_place: "mllm/backends/qnn/custom-op-package/LLaMAPackage"
      targets:
        - "htp_aarch64"
        - "htp_v75"

  - CMakeConfigTask:
      cmake_cfg_path: "build-android-arm64-v8a-qnn"
      cmake_build_type: "Release"
      cmake_toolchain_file: "$ANDROID_NDK_PATH/build/cmake/android.toolchain.cmake"
      cmake_extra_args:
        - "-DMLLM_CROSS_COMPILE=ON"
        - "-DMLLM_BUILD_ARM_BACKEND=ON"
        - "-DMLLM_BUILD_QNN_BACKEND=ON"
        - "-DANDROID_PLATFORM=android-28"
        - "-DANDROID_ABI=arm64-v8a"
        - '-DMLLM_CPU_BACKEND_COMPILE_OPTIONS="-march=armv8.2-a+fp16+fp16fml+dotprod+i8mm;-ffast-math;-Wno-nan-infinity-disabled"'
        - "-DCMAKE_INSTALL_PREFIX=/root/mllm-install-android-arm64-v8a-qnn"
        - "-DMLLM_KERNEL_USE_THREADS=ON"
        - "-DMLLM_KERNEL_THREADS_VENDOR_OPENMP=ON"
        - "-DMLLM_KERNEL_USE_THREADS_VENDOR_MLLM=OFF"

  - CMakeBuildTask:
      cmake_cfg_path: "build-android-arm64-v8a-qnn"

  - CMakeInstallTask:
      cmake_cfg_path: "build-android-arm64-v8a-qnn"
